In [1]:
import numpy as np

In [2]:
#this notebook tries implimentation of linear algebra
# it solves matrix by backsubsitution 

In [16]:
def gausElim(a , b):
    n = len(b)
    #elimination phase...
    #here we transform the matrix to upper triangular matrix
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a [i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                b[i] = b[i] - lam*b[k]
    # Back substitution
    #upper triangular matrix is solved by back subsitution
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

In [10]:
#what if the value of b is B or is of more than 2 size
def vandermode(v):
    n = len(v)
    a = np.zeros((n,n),dtype=float)
    for j in range(n):
        a[:,j] = v**(n-j-1)
    return a

In [35]:
# test the equation

v = np.array([1.0, 1.2, 1.4, 1.6, 1.8, 2.0])
b = np.array([0.0, 1.0, 0.0, 1.0, 0.0, 1.0])
a = vandermode(v)

In [36]:
a

array([[ 1.     ,  1.     ,  1.     ,  1.     ,  1.     ,  1.     ],
       [ 2.48832,  2.0736 ,  1.728  ,  1.44   ,  1.2    ,  1.     ],
       [ 5.37824,  3.8416 ,  2.744  ,  1.96   ,  1.4    ,  1.     ],
       [10.48576,  6.5536 ,  4.096  ,  2.56   ,  1.6    ,  1.     ],
       [18.89568, 10.4976 ,  5.832  ,  3.24   ,  1.8    ,  1.     ],
       [32.     , 16.     ,  8.     ,  4.     ,  2.     ,  1.     ]])

In [37]:
b

array([0., 1., 0., 1., 0., 1.])

In [38]:
xx = gausElim(a,b)

In [39]:
xx

array([   416.66666667,  -3125.00000004,   9250.00000012, -13500.00000017,
         9709.33333345,  -2751.00000003])

In [43]:

aOrig = a.copy() # Save original matrix
bOrig = b.copy() # and the constant vector
x = gausElim(a,b)
det = np.product(np.diagonal(a))
print(f"x =\n   {x}")
print(f"\n det =  {det}")


x =
   [ -257.96034624   807.81916732  1170.71683355 -1424.87904926
 -4787.52325539  4723.96307867]

 det =  -10949338.41009368


In [42]:
print(f"\n Check result: [a]  - b =\n, {np.dot(aOrig,x) - bOrig}")
# matrixmultiply


 Check result: [a]  - b =
, [-1.09139364e-11  7.41238182e-11 -8.73114914e-11 -2.25554686e-10
 -2.32830644e-10  3.20142135e-10]
